### ISSUE TITLE
Error when installing pyopencl and oclgrind-binary-distribution

### ISSUE THREAD

**Issue by sinsemellan** [isuruf/ocl-wheels#3]
We tried to install pyopencl and oclgrind-binary-distribution together on debian buster. The installation of oclgrind-binary-distribution does not succeed and the following error is shown:
```
ERROR: Could not install packages due to an EnvironmentError: [Errno 20] Not a directory: '/usr/local/lib/python3.7/site-packages/pyopencl/.libs/oclgrind.icd'
```
The problem is, that the pyopencl package creates a **file** ```/usr/local/lib/python3.7/site-packages/pyopencl/.libs``` and then the package oclgrind-binary-distribution tries to add the file oclgrind.icd to the **directory** ```/usr/local/lib/python3.7/site-packages/pyopencl/.libs/oclgrind.icd```.

A workaround is to install the pyopencl package, then delete the file ```/usr/local/lib/python3.7/site-packages/pyopencl/.libs``` manually and then install the package oclgrind-binary-distribution.

We looked at the contents of these packages:
https://pypi.org/project/pyopencl/#files
https://pypi.org/project/oclgrind-binary-distribution/#files

**Comment by isuruf** [comment]
Thanks for the bug report. Will fix when I get some time

**Comment by simo1427** [comment]
I am experiencing the same issue but with python 3.8. Despite the inability to install oclgrind through pip, I was able to run the debugger by installing it with the system's package manager and passing the option `-cl-opt-disable` to the OpenCL compiler. The command is `PYOPENCL_BUILD_OPTIONS=-cl-opt-disable oclgrind -i python3 ./opencl.py`. It runs the interactive debugger, but should you opt not to use it, you can always remove -i.

**Comment by isuruf** [comment]
should be fixed now
