### ISSUE TITLE
Provide minimal instructions?

### ISSUE THREAD

**Issue by inducer** [isuruf/ocl-wheels#4]
I tried to work my way around updating this (context: https://github.com/inducer/meshmode/pull/194/checks?check_run_id=2647133257#step:5:27), but it didn't feel like a good use of time without a vague idea of where stuff was supposed to go. Could you add a README with a few steps?

**Comment by isuruf** [comment]
Yes, I'll add a README.

Btw, that looks like an issue with opencl library in the github runner. It's building pyopencl from source and `clSetProgramSpecializationConstant` is missing.

**Comment by inducer** [comment]
Thanks!

And you're right. The issue is that ocl-icd declares but doesn't define a symbol. (My current plan for a hack-around: https://github.com/inducer/pyopencl/pull/475)

**Comment by isuruf** [comment]
ocl-icd does define the symbol `clSetProgramSpecializationConstant` though.

I get the following.
```bash
nm -g /home/idf2/miniconda3/envs/pyopencl/lib/python3.8/site-packages/pyopencl/.libs/libOpenCL-eef607b8.so.1.0.0 | grep "clSetProgramSpecializationConstant"
0000000000014a70 T clSetProgramSpecializationConstant
```

Maybe in the github runner, the opencl headers and the library are mismatched. I see that pyopencl wheels were just uploaded and maybe this error will go away.

**Comment by inducer** [comment]
I misinterpreted what's in https://pypi.org/project/pocl-binary-distribution/. That version of pocl doesn't define that symbol:
```
 nm --dynamic pyopencl/.libs/libpocl-3a06e60a.so | grep Specialization   
```
But I was *also* wrong to implicate this package at all: That CI job uses [*some* ocl-icd/pocl from the Ubuntu CI image](https://github.com/inducer/meshmode/blob/fix-oct2py-wait/.ci/install-for-firedrake.sh#L5).

**Comment by isuruf** [comment]
I just tried those 2 packages on a ubuntu-20.04 docker image and it gives me OpenCL 2.2 headers and a OpenCL 2.1 library.

**Comment by inducer** [comment]
Yeah, that sounds plausible. https://github.com/inducer/meshmode/pull/194/commits/17041473fcf0bfa840bc2838920e31e7b31dfd6e seems to have done the trick, at least for *that* fire. :)

**Comment by inducer** [comment]
And thanks for checking!

**Comment by isuruf** [comment]
There's a README now
